### ISSUE TITLE
Publish latest changes to crates.io

### ISSUE THREAD

**Issue by vinc** [bfrog/transitfeed#12]
Hi, I created a tool last year depending on the version of transitfeed in the repo and I was hopping that it'd get published at some point so I could publish my project on crates.io but that hasn't been the case yet. Do you thing it'd be possible to publish a new release with the changes?

This is my project that depend on transitfeed: https://github.com/vinc/timetable

Thanks!

**Comment by bfrog** [comment]
Of course, will try to get this out on crates today

**Comment by bfrog** [comment]
Done, 0.3.0 is out there
